import { StyleSheet } from 'react-native';

// F12 — MediaHero.tsx'ten çıkarıldı (400 satır kuralı, AI_RULES §1).
// Saf stil tanımı, mantık yok.
export const styles = StyleSheet.create({
  container: {
    backgroundColor: 'transparent',
  },
  backdropContainer: {
    height: 280,
    width: '100%',
    position: 'relative',
  },
  backdropImage: {
    width: '100%',
    height: '100%',
  },
  backdropPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#172033',
  },
  gradientOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 180,
  },
  backButton: {
    position: 'absolute',
    left: 20,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeButton: {
    position: 'absolute',
    right: 64,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionsButton: {
    position: 'absolute',
    right: 16,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentContainer: {
    flexDirection: 'row',
    marginTop: -80,
    zIndex: 5,
  },
  progressContainer: {
    marginTop: 16,
    width: '100%',
    maxWidth: 240,
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressBarWrapper: {
    flex: 1,
  },
  progressText: {
    color: '#a3a3a3',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 8,
  },
  posterImage: {
    width: 110,
    height: 165,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A364F',
  },
  posterPlaceholder: {
    width: 110,
    height: 165,
    borderRadius: 8,
    backgroundColor: '#172033',
  },
  textContainer: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'flex-end',
    paddingBottom: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 4,
  },
  meta: {
    fontSize: 13,
    color: '#a3a3a3',
    marginBottom: 4,
  },
  genres: {
    fontSize: 13,
    color: '#a3a3a3',
    marginBottom: 12,
  },
  ratingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    rowGap: 8,
    columnGap: 10,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(250, 204, 21, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(250, 204, 21, 0.2)',
  },
  ratingText: {
    color: '#facc15',
    fontWeight: 'bold',
    fontSize: 13,
    marginLeft: 4,
  },
  userRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(163, 163, 163, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    minHeight: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(163, 163, 163, 0.2)',
  },
  // Sadece ikon barındıran rozetler: metin olmadığı için dokunma alanı
  // önerilen 44pt'nin çok altında kalıyordu — biraz genişletildi.
  iconOnlyBadge: {
    minWidth: 32,
    justifyContent: 'center',
  },
  userRatingActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  userRatingText: {
    color: '#a3a3a3',
    fontWeight: '500',
    fontSize: 13,
    marginLeft: 4,
  },
  userRatingTextActive: {
    color: '#3b82f6',
    fontWeight: 'bold',
  },
  watchlistSection: {
    marginTop: 14,
  },
  watchlistBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 46,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  watchlistBtnActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderColor: 'rgba(59, 130, 246, 0.35)',
  },
  watchlistBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  watchlistBtnTextActive: {
    color: '#3b82f6',
  },
  overviewSection: {
    padding: 16,
    marginTop: 8,
  },
  overviewText: {
    color: '#d4d4d4',
    fontSize: 14,
    lineHeight: 22,
  },
  trailerSection: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  trailerContainer: {
    height: 180,
    width: '100%',
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  trailerImage: {
    width: '100%',
    height: '100%',
  },
  trailerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
